# Generated by Django 4.2.2 on 2023-06-24 21:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0010_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='image',
        ),
        migrations.AddField(
            model_name='task',
            name='images',
            field=models.ManyToManyField(related_name='tasks', to='crm.image'),
        ),
        migrations.AlterField(
            model_name='image',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_images', to='crm.task'),
        ),
    ]
