# Generated by Django 4.2.2 on 2023-06-25 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0011_remove_task_image_task_images_alter_image_task'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
